sudo: required

services:
    - docker

before_install:
    - docker build -t anupmahajan/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -t anupmahajan/react-test npm run test -- --coverage

after_success:
    - docker build -t amahadocker/multi-client ./client
    - docker build -t amahadocker/multi-nginx  ./nginx
    - docker build -t amahadocker/multi-server ./server
    - docker build -t amahadocker/multi-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push amahadocker/multi-client
    - docker push amahadocker/multi-nginx
    - docker push amahadocker/multi-server
    - docker push amahadocker/multi-worker
